version: '3.9'
services:
  nginx: 
    ports:
      - 80:80
      
  redis:
    command: 
     - '--requirepass ${REDIS_PASSWORD}'
    environment:
      - REDIS_REPLICATION_MODE=master

  database:
    ports:
      - ${DB_DATABASE:-5432}:5432