version: '3.9'
services:
  nginx: 
    ports:
      - 80:80

  database:
    ports:
      - ${DB_PORT:-5432}:5432

  adminer:
    image: adminer
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - 8080:8080